name: Deploy Beta
on:
  workflow_call:
    inputs:
      fastlane-lane:
        required: true
        type: string
      silent:
        default: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  output-something:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - run: echo "${{ inputs.fastlane-lane }}"
  dev-slack:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    if: ${{ inputs.silent != 'true' && inputs.fastlane-lane == 'beta_dev' }}
    steps:
      - run: echo "lane was beta_dev"
  client-slack:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    if: ${{ inputs.silent != 'true' && inputs.fastlane-lane == 'beta' }}
    steps:
      - run: echo "lane was beta"
