name: (On Dispatch) Deploy Beta
on:
  workflow_dispatch:
    inputs:
      group:
        type: choice
        description: Where to deploy to
        options:
          - dev
          - client
      silent:
        type: boolean
        description: Skip notifications

jobs:
  something-failing:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  send-slack:
    needs: something-failing
    runs-on: ubuntu-latest
    if: github.event.inputs.silent != 'true' && failure()
    steps:
      - run: echo "dev chosen"
