name: Workflow dispatch
on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: string
      choice:
        required: true
        type: choice
        options:
          - '1'
          - '2'
          - '3'

jobs:
  fetch-branch-name:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    outputs:
      branch: ${{ steps.branch-name.outputs.branch }}
    steps:
      - id: branch-name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      - name: Try to fail
        run: exit 1
  main:
    runs-on: ubuntu-latest
    needs: fetch-branch-name
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.fetch-branch-name.outputs.branch }}
      - run: echo "fetched branch named ${{ needs.fetch-branch-name.outputs.branch }}"
